[package]
name = "crypto"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
ripemd = "0.1"
hmac = "0.12"
pbkdf2 = "0.12"
secp256k1 = { version = "0.28", features = ["rand", "serde"] }
rand = "0.8"

bip39 = {version = "2",features=["rand"]}